controller_list:
  - name: fake_LeftArm_controller
    joints:
      - left_clavicle_roll
      - left_clavicle_pitch
      - left_clavicle_yaw
      - left_shoulder_roll
      - left_shoulder_pitch
      - left_shoulder_yaw
      - left_elbow_roll
      - left_elbow_pitch
      - left_elbow_yaw
      - left_hand_roll
      - left_hand_pitch
      - left_hand_yaw